### PR TITLE
Created a website for the project.

### PR DESCRIPTION
**Pull request by swarupsahu08**

### CODE REVIEW

**Review by eeshan15 — CHANGES_REQUESTED** [review]
Please do add a screenshot of the website that you have hosted in the PR also add title and some sort of description of what you have done. Re-upload with changes in order to get merged. Please Create a new pr  am generating a new issue for that thank you .@swarupsahu08

**Comment by swarupsahu08** [comment]
@eeshan15 Ok let me do this Can I create a PR another time

**Comment by eeshan15** [comment]
Sure whenever you are free please add a PR accordingly @swarupsahu08

**Comment by swarupsahu08** [comment]
> Sure whenever you are free please add a PR accordingly @swarupsahu08

@eeshan15 Yah now You can check the pull request

**Pull request closed without merging**
