### PR TITLE
Added the files for the website of this project with link of the repository at the end.

### LINKED ISSUE #13: Website generation of the project Credit Risk Analysis
Generate a website for the credit risk analysis project which tells about the project briefly.

### PR DESCRIPTION
**Pull request by swarupsahu08**
It is for the issue #13 
Here I have provided the comments in the code for anyone to understand
I have used javascript to render a bargraph i.e actually for the  analysis
I have described about the objective of the project and given the link to the github repository
Screenshot 2024-10-13 190852
Screenshot 2024-10-13 192320
Screenshot 2024-10-13 192425

### CODE REVIEW

**Comment by eeshan15** [comment]
Can you give me a link where you have hosted it ? @swarupsahu08 please provide the link after reviewing the website it will be merged.

**Comment by swarupsahu08** [comment]
> Can you give me a link where you have hosted it ? @swarupsahu08 please provide the link after reviewing the website it will be merged.

I think you can test it yourself with the github pages

**Comment by swarupsahu08** [comment]
> Can you give me a link where you have hosted it ? @swarupsahu08 please provide the link after reviewing the website it will be merged.

@eeshan15 Here is the link you can check how it looks https://swarupsahu08.github.io/Credit-Risk-Analysis/

**Comment by swarupsahu08** [comment]
@eeshan15 did you see the Pull request

**Comment by eeshan15** [comment]
@swarupsahu08 I saw the link and its kind of basic but a good deal thank you for your service mate. Your PR is being merged and issue has been solved. Thank you.

**Review by eeshan15 — COMMENTED** [review]
Great work

**Comment by swarupsahu08** [comment]
thanks @eeshan15 but ,I think in future I may need help with getting started in data science Can you help me to get started

**Comment by eeshan15** [comment]
Yeah will do kindly check the hacktoberfest.com website

**Pull request merged**
